### ISSUE TITLE
setup.py python_requires string fails parsers

### ISSUE THREAD

**Issue by ghost** [jvanasco/bleach_extras#3]
https://github.com/jvanasco/bleach_extras/blob/93c54f936158e646795fb94a89c8e671044b0e47/setup.py#L48

the setup string from 
`python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, , !=3.5.*",`

is incorrectly formatted with an double comma empty entry.  This breaks a number of Version Constraint parsers in tools such as `poetry`

I imagine that the correct string should be something akin to
`python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*",`

**Comment by jvanasco** [comment]
Thanks for catching this. I've pushed the updated string to main, is there any way you can test it?  I don't use poetry, and this hasn't been an issue for me, so I have no idea how to test.  If you can confirm it works, I'll close this issue and do a versionbump to pypi.

**Comment by ghost** [comment]
looks good

**Comment by jvanasco** [comment]
Released in `v0.1.1` tag + PyPi
